---
- name: Example3
  hosts: yandex_cloud

  tasks:
  - name: install git
    ansible.builtin.apt:
      name: git-all
      state: present
      update_cache: yes
    become: yes
    tags: installer
      	
  - name: install make
    ansible.builtin.apt:
      name: make
      state: present
    become: yes
    tags: installer
    
  - name: install nodejs
    ansible.builtin.apt:
      name:  nodejs
      state: present
    become: yes
    tags: installer
    
  - name: add user arya
    ansible.builtin.user:
      name: arya
      comment: Arya
      tags: users

  - name: add user sansa
    ansible.builtin.user:
      name: sansa
      comment: Sansa
      tags: users

  - name: add user tirion
    ansible.builtin.user:
      name: tirion
      comment: Tirion
      tags: users      