---
- name: Example1
  hosts: yandex_cloud


  tasks:
  - name: install git
    ansible.builtin.apt:
      name: git-all
      state: present
      update_cache: yes
    become: yes
      	
      	
      	
